2025-01-26 04:08:31,769 - INFO - Loading the 'squad' dataset...
2025-01-26 04:08:41,917 - ERROR - An unexpected error occurred: module 'openai' has no attribute 'error'
2025-01-26 04:10:24,098 - INFO - Loading the 'squad' dataset...
2025-01-26 04:10:36,549 - ERROR - Request 0 encountered an exception: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
. Attempt 1/3
2025-01-26 04:10:36,549 - ERROR - Request 0 failed after 3 attempts.
2025-01-26 04:10:36,549 - ERROR - Request 1 encountered an exception: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
. Attempt 1/3
2025-01-26 04:10:36,549 - ERROR - Request 1 failed after 3 attempts.
2025-01-26 04:10:36,549 - ERROR - Request 2 encountered an exception: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
. Attempt 1/3
2025-01-26 04:10:36,549 - ERROR - Request 2 failed after 3 attempts.
2025-01-26 04:10:36,549 - ERROR - Request 3 encountered an exception: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
. Attempt 1/3
2025-01-26 04:10:36,549 - ERROR - Request 3 failed after 3 attempts.
2025-01-26 04:10:36,549 - ERROR - Request 4 encountered an exception: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
. Attempt 1/3
2025-01-26 04:10:36,549 - ERROR - Request 4 failed after 3 attempts.
2025-01-26 04:10:36,549 - ERROR - Request 5 encountered an exception: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
. Attempt 1/3
2025-01-26 04:10:36,549 - ERROR - Request 5 failed after 3 attempts.
2025-01-26 04:10:36,549 - ERROR - Request 6 encountered an exception: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
. Attempt 1/3
2025-01-26 04:10:36,550 - ERROR - Request 6 failed after 3 attempts.
2025-01-26 04:10:36,550 - ERROR - Request 7 encountered an exception: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
. Attempt 1/3
2025-01-26 04:10:36,550 - ERROR - Request 7 failed after 3 attempts.
2025-01-26 04:10:36,550 - ERROR - Request 8 encountered an exception: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
. Attempt 1/3
2025-01-26 04:10:36,550 - ERROR - Request 8 failed after 3 attempts.
2025-01-26 04:10:36,550 - ERROR - Request 9 encountered an exception: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
. Attempt 1/3
2025-01-26 04:10:36,550 - ERROR - Request 9 failed after 3 attempts.
2025-01-26 04:10:36,550 - INFO - 
Total time for 10 requests: 0.00s
Average request time: 0.0000s
Successful requests: 0/10
2025-01-26 04:10:36,551 - INFO - Metrics:
{}
2025-01-26 04:10:36,553 - INFO - Inference results saved to: result/llama3.2_1b_async.json
2025-01-26 04:11:56,003 - INFO - Loading the 'squad' dataset...
2025-01-26 04:12:05,119 - INFO - message='OpenAI API response' path=http://localhost:8000/v1/chat/completions processing_ms=None request_id=None response_code=404
2025-01-26 04:12:05,120 - ERROR - Request 7 encountered an exception: Invalid response object from API: '{"object":"error","message":"The model `llama-3.2-1b` does not exist.","type":"NotFoundError","param":null,"code":404}' (HTTP response code was 404). Attempt 1/3
2025-01-26 04:12:05,120 - ERROR - Request 7 failed after 3 attempts.
2025-01-26 04:12:05,120 - INFO - message='OpenAI API response' path=http://localhost:8000/v1/chat/completions processing_ms=None request_id=None response_code=404
2025-01-26 04:12:05,120 - INFO - message='OpenAI API response' path=http://localhost:8000/v1/chat/completions processing_ms=None request_id=None response_code=404
2025-01-26 04:12:05,120 - INFO - message='OpenAI API response' path=http://localhost:8000/v1/chat/completions processing_ms=None request_id=None response_code=404
2025-01-26 04:12:05,121 - INFO - message='OpenAI API response' path=http://localhost:8000/v1/chat/completions processing_ms=None request_id=None response_code=404
2025-01-26 04:12:05,121 - INFO - message='OpenAI API response' path=http://localhost:8000/v1/chat/completions processing_ms=None request_id=None response_code=404
2025-01-26 04:12:05,121 - INFO - message='OpenAI API response' path=http://localhost:8000/v1/chat/completions processing_ms=None request_id=None response_code=404
2025-01-26 04:12:05,121 - INFO - message='OpenAI API response' path=http://localhost:8000/v1/chat/completions processing_ms=None request_id=None response_code=404
2025-01-26 04:12:05,121 - INFO - message='OpenAI API response' path=http://localhost:8000/v1/chat/completions processing_ms=None request_id=None response_code=404
2025-01-26 04:12:05,121 - INFO - message='OpenAI API response' path=http://localhost:8000/v1/chat/completions processing_ms=None request_id=None response_code=404
2025-01-26 04:12:05,121 - ERROR - Request 6 encountered an exception: Invalid response object from API: '{"object":"error","message":"The model `llama-3.2-1b` does not exist.","type":"NotFoundError","param":null,"code":404}' (HTTP response code was 404). Attempt 1/3
2025-01-26 04:12:05,121 - ERROR - Request 6 failed after 3 attempts.
2025-01-26 04:12:05,122 - ERROR - Request 4 encountered an exception: Invalid response object from API: '{"object":"error","message":"The model `llama-3.2-1b` does not exist.","type":"NotFoundError","param":null,"code":404}' (HTTP response code was 404). Attempt 1/3
2025-01-26 04:12:05,122 - ERROR - Request 4 failed after 3 attempts.
2025-01-26 04:12:05,122 - ERROR - Request 5 encountered an exception: Invalid response object from API: '{"object":"error","message":"The model `llama-3.2-1b` does not exist.","type":"NotFoundError","param":null,"code":404}' (HTTP response code was 404). Attempt 1/3
2025-01-26 04:12:05,122 - ERROR - Request 5 failed after 3 attempts.
2025-01-26 04:12:05,122 - ERROR - Request 3 encountered an exception: Invalid response object from API: '{"object":"error","message":"The model `llama-3.2-1b` does not exist.","type":"NotFoundError","param":null,"code":404}' (HTTP response code was 404). Attempt 1/3
2025-01-26 04:12:05,122 - ERROR - Request 3 failed after 3 attempts.
2025-01-26 04:12:05,122 - ERROR - Request 2 encountered an exception: Invalid response object from API: '{"object":"error","message":"The model `llama-3.2-1b` does not exist.","type":"NotFoundError","param":null,"code":404}' (HTTP response code was 404). Attempt 1/3
2025-01-26 04:12:05,122 - ERROR - Request 2 failed after 3 attempts.
2025-01-26 04:12:05,122 - ERROR - Request 1 encountered an exception: Invalid response object from API: '{"object":"error","message":"The model `llama-3.2-1b` does not exist.","type":"NotFoundError","param":null,"code":404}' (HTTP response code was 404). Attempt 1/3
2025-01-26 04:12:05,122 - ERROR - Request 1 failed after 3 attempts.
2025-01-26 04:12:05,122 - ERROR - Request 0 encountered an exception: Invalid response object from API: '{"object":"error","message":"The model `llama-3.2-1b` does not exist.","type":"NotFoundError","param":null,"code":404}' (HTTP response code was 404). Attempt 1/3
2025-01-26 04:12:05,122 - ERROR - Request 0 failed after 3 attempts.
2025-01-26 04:12:05,122 - ERROR - Request 9 encountered an exception: Invalid response object from API: '{"object":"error","message":"The model `llama-3.2-1b` does not exist.","type":"NotFoundError","param":null,"code":404}' (HTTP response code was 404). Attempt 1/3
2025-01-26 04:12:05,123 - ERROR - Request 9 failed after 3 attempts.
2025-01-26 04:12:05,123 - ERROR - Request 8 encountered an exception: Invalid response object from API: '{"object":"error","message":"The model `llama-3.2-1b` does not exist.","type":"NotFoundError","param":null,"code":404}' (HTTP response code was 404). Attempt 1/3
2025-01-26 04:12:05,123 - ERROR - Request 8 failed after 3 attempts.
2025-01-26 04:12:05,123 - INFO - 
Total time for 10 requests: 0.00s
Average request time: 0.0000s
Successful requests: 0/10
2025-01-26 04:12:05,124 - INFO - Metrics:
{}
2025-01-26 04:12:05,125 - INFO - Inference results saved to: result/llama3.2_1b_async.json
